### ISSUE TITLE
generate

### ISSUE THREAD

**Issue by letarg0** [PatrickLib/captcha_recognition#11]
I get this

```
$python ./captcha_gen_default.py 
>> generate 1000 captchas in ./data/test_data
Traceback (most recent call last):
  File "./captcha_gen_default.py", line 55, in <module>
    gen(FLAGS.test_dir, TEST_SIZE, CHARS_NUM)
  File "./captcha_gen_default.py", line 28, in gen
    for i in xrange(total_size):
NameError: name 'xrange' is not defined
```

what I can to do?

**Comment by rayhk6** [comment]
change xrange to range
